## This configuration file contains information required by any web
## service that makes use of the CAS server for authentication.

authentication:

  ## Use this configuration option if the CAS server is on a host different
  ## from the console-auth server.
  # cas_host: ip-10-224-3-144.us-west-2.compute.internal:443

  ## The port CAS is listening on.  This is ignored if cas_host is set.
  # cas_port: 443

  ## The session secret is randomly generated during installation of Puppet
  ## Enterprise and will be regenerated any time console-auth is enabled or disabled.
  session_key: 'puppet_enterprise_console'
  session_secret: 5020e6e672721bde59ac4679cbdb299e71015f31623d4eeafdbe057280e386cfe6e3c691d34bbb4603f4fc2591e7f7c968ce3eca1113c095eeb132d3c602a492

  ## Set this to true to allow anonymous users read-only access to all of
  ## Puppet Enterprise Console.
  global_unauthenticated_access: false

authorization:
  local:
    default_role: read-only
    description: Local
#  ldap:
#    default_role: read-only
#    description: LDAP
#  activedirectoryldap:
#    default_role: read-only
#    description: Active Directory
#  google:
#    default_role: read-only
#    description: Google
